### ISSUE TITLE
Using LDAP authentication in ZMI

### ISSUE THREAD

**Issue by JorgeMerchan** [plone/plone.app.ldap#23]
Is there a way to use this plugin to authenticate in the ZMI?, for now ZMI only authenticates with the "users" plugin.

**Comment by mauritsvanrees** [comment]
Short answer, if I understand your question correctly: no.

Long answer:

With the ZMI you mean the ZMI in the Zope root, right? Because if your plone site is at http://localhost:8080/Plone and you have installed plone.app.ldap in it, then visiting http://localhost:8080/Plone/manage_main should bring you to the Plone login form, where LDAP works just fine when correctly configured.

But visiting http://localhost:8080/manage_main in the Zope root would usually trigger a basic authentication popup instead. plone.app.ldap is not available at that level, because it is not installed at that level. You could install plone.app.ldap in the Plone Site and check the changes it does in http://localhost:8080/Plone/acl_users/manage_main. Then you can see if you can manually do those changes in the top level Zope acl_users at http://localhost:8080/acl_users/manage_main. You would not really be using plone.app.ldap then, but its dependencies LDAPMultiPlugins and LDAPUserFolder.
